highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Alma Eguizabal's Resume
name: Alma Eguizabal
email: alma.eguizabal@ieee.org
email_full: mailto:alma.eguizabal@ieee.org
website: https://almaegui.github.io/
website_full: https://almaegui.github.io/
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.com/maps/place/Paderborn'
address:
  street: Warburger Str. 100
  postcode: 33098
  city: Paderborn
  country: Germany
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
